project:
  type: website
  output-dir: docs
  
  
website:
  title: "Precision Workshop"
  sidebar:
    style: "floating"
    search: true
    contents:
      - 0.1_R_Installation.qmd
      - 0.2_Further_Reading.qmd
      - 1.1_R_Intro.qmd
      - 1.2_Data_Wrangling.qmd
      - 1.3_Data_Visualization.qmd

format:
  html:
    theme: cosmo
  
